[[main]]
  name = "O mnie"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projekty"
  url = "#projects"
  weight = 30

[[main]]
  name = "Prezentacje"
  url = "#talks"
  weight = 40

[[main]]
  name = "Publikacje"
  url = "#publications"
  weight = 40

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 60

[[main]]
  name = "Materiały"
  url = "materialy/"
  weight = 50

