---
language: ruby

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.58.3_Linux-64bit.deb

script:
  - ls

deploy:
  - provider: script
    script: chmod +x deploy.sh && ./deploy.sh
    skip_cleanup: true
    on:
      branch: master
